// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.lan_bridge_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LanBridgeNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 一台已配对的电脑（手机侧保存）。
 *
 * **不含会话令牌**：令牌只留在原生侧，Dart 层不需要也不应该拿到它。
 * 这里只暴露"给用户看和给用户删"所需的最小信息。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LanPairedPc (
  /** 电脑名，来自握手时 `hello.clientName`。配对成功前是地址。 */
  val name: String,
  val host: String,
  val port: Long,
  /** 上次成功配对/连接的时间戳（毫秒）。 */
  val lastConnectedAtMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LanPairedPc {
      val name = pigeonVar_list[0] as String
      val host = pigeonVar_list[1] as String
      val port = pigeonVar_list[2] as Long
      val lastConnectedAtMs = pigeonVar_list[3] as Long
      return LanPairedPc(name, host, port, lastConnectedAtMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      host,
      port,
      lastConnectedAtMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LanPairedPc) {
      return false
    }
    if (this === other) {
      return true
    }
    return LanBridgeNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * 「局域网直连」页要展示的状态。
 *
 * 页面靠轮询 [LanBridgeNative.getStatus] 刷新；被拒绝的原因也在这里回传，
 * 因为 `reject` 是电脑发给手机的原生帧，Dart 侧看不到（docs/desktop_bridge_lan_CN.md §8.4、§9.3）。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LanBridgeStatus (
  /** USB 链路是否已连上（与 LAN 互斥，共用一个客户端槽位）。 */
  val usbConnected: Boolean,
  /** LAN 链路是否已连上。 */
  val lanConnected: Boolean,
  /** 是否已经设定了拨号目标（不代表已连上）。 */
  val hasTarget: Boolean,
  val targetHost: String? = null,
  val targetPort: Long,
  /** 已连接/正在连接的电脑名。 */
  val peerName: String? = null,
  /** 最近一次被电脑拒绝的错误码：`code` / `code-stale` / `locked` / `busy`（§8.4）。 */
  val lastRejectCode: String? = null,
  val lastRejectMessage: String? = null,
  val autoReconnect: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LanBridgeStatus {
      val usbConnected = pigeonVar_list[0] as Boolean
      val lanConnected = pigeonVar_list[1] as Boolean
      val hasTarget = pigeonVar_list[2] as Boolean
      val targetHost = pigeonVar_list[3] as String?
      val targetPort = pigeonVar_list[4] as Long
      val peerName = pigeonVar_list[5] as String?
      val lastRejectCode = pigeonVar_list[6] as String?
      val lastRejectMessage = pigeonVar_list[7] as String?
      val autoReconnect = pigeonVar_list[8] as Boolean
      return LanBridgeStatus(usbConnected, lanConnected, hasTarget, targetHost, targetPort, peerName, lastRejectCode, lastRejectMessage, autoReconnect)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      usbConnected,
      lanConnected,
      hasTarget,
      targetHost,
      targetPort,
      peerName,
      lastRejectCode,
      lastRejectMessage,
      autoReconnect,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LanBridgeStatus) {
      return false
    }
    if (this === other) {
      return true
    }
    return LanBridgeNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class LanBridgeNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LanPairedPc.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LanBridgeStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LanPairedPc -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LanBridgeStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 手机端「局域网直连」的原生接口。
 *
 * 这些方法都很快（只读写内存状态与 SharedPreferences），因此不加 `@async`。
 * 真正的拨号在原生侧的独立线程里跑，不阻塞这里。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LanBridgeNative {
  /** 页面轮询当前状态。 */
  fun getStatus(): LanBridgeStatus
  /**
   * 用**用户输入的 6 位校验码**连接指定电脑（首次配对）。
   *
   * 调用即返回；拨号在后台按 1s→2s→4s… 退避重试，直到连上或用户断开。
   */
  fun connectWithCode(host: String, port: Long, code: String)
  /**
   * 用**已保存的会话令牌**重连一台已配对的电脑。
   *
   * 与 [connectWithCode] 的区别只在出示什么凭据；地址变了就不该走这里（§11.4）。
   */
  fun reconnectTo(host: String, port: Long)
  /** 主动断开 LAN 并清除拨号目标（保留已配对记录）。 */
  fun disconnect()
  /** 已配对的电脑列表。 */
  fun listPairedPcs(): List<LanPairedPc>
  /**
   * 忘掉一台电脑（连同它的令牌）。若它正连着，一并断开。
   * @return 是否确实删掉了一条。
   */
  fun forgetPc(host: String, port: Long): Boolean
  /** 忘记全部。 */
  fun forgetAllPcs()
  /** 是否在 App 启动与断线后自动重连。 */
  fun setAutoReconnect(enabled: Boolean)

  companion object {
    /** The codec used by LanBridgeNative. */
    val codec: MessageCodec<Any?> by lazy {
      LanBridgeNativePigeonCodec()
    }
    /** Sets up an instance of `LanBridgeNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LanBridgeNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.connectWithCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hostArg = args[0] as String
            val portArg = args[1] as Long
            val codeArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.connectWithCode(hostArg, portArg, codeArg)
              listOf(null)
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.reconnectTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hostArg = args[0] as String
            val portArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.reconnectTo(hostArg, portArg)
              listOf(null)
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.listPairedPcs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listPairedPcs())
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.forgetPc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hostArg = args[0] as String
            val portArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.forgetPc(hostArg, portArg))
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.forgetAllPcs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.forgetAllPcs()
              listOf(null)
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.LanBridgeNative.setAutoReconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setAutoReconnect(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              LanBridgeNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
